"""empty message

Revision ID: bc3a7def3fb3
Revises: 366e11dec3cc
Create Date: 2018-06-11 00:45:55.394564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc3a7def3fb3'
down_revision = '366e11dec3cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bought', sa.Column('quiz_id', sa.Integer(), nullable=True))
    op.add_column('notbought', sa.Column('quiz_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notbought', 'quiz_id')
    op.drop_column('bought', 'quiz_id')
    # ### end Alembic commands ###
